### ISSUE TITLE
inconsistant startup position and content with multiple PanelWindow in one file

### ISSUE THREAD

**Issue by littleblack111** [quickshell-mirror/quickshell#125]
just two PanelWindow in one file, any content in it will be misplaced in initial launch, try text for example. the misplace will be fixed with a reload, however it's wrong every time you launch the shell initially

**Comment by outfoxxed** [comment]
You're going to have to provide an example snippet because this doesn't happen to everyone.

**Comment by littleblack111** [comment]
shell.qml:
```
import Quickshell
import QtQuick

Scope {
    PanelWindow {
        anchors.top: true
        Text {
            text: "test 1"
        }
    }
    PanelWindow {
        anchors.top: true
        Text {
            text: "test 2"
        }
    }
}
```

[example video](https://drive.google.com/file/d/1YZPWHJl27vVVlFfKtMk4w-5KOhsoRxoc/view?usp=sharing)

**Comment by littleblack111** [comment]
@outfoxxed Is the MRE sufficient? Does it trigger on ur computer?

**Comment by outfoxxed** [comment]
I can't currently reproduce it from the sample. It might've been fixed here or upstream, I don't remember.

**Comment by littleblack111** [comment]
> I can't currently reproduce it from the sample. It might've been fixed here or upstream, I don't remember.

i can still reproduce this with latest -git, I also discovered a similar misplacement bug with PopupWindow(couldn't get a simple MRE)

FWIW after running either of those bugs, reloading will give
```
WARN: QWaylandGLContext::makeCurrent: eglError: 0x3009, this: 0x7f083c3ab180 

  WARN: QRhiGles2: Failed to make context current. Expect bad things to happen.
  WARN: QWaylandGLContext::makeCurrent: eglError: 0x3009, this: 0x7f083c3ab180 

  WARN: QRhiGles2: Failed to make context current. Expect bad things to happen.
```
could this be related to what gpu i'm using?(I'm using nvidia with propitiatory driver)

**Comment by Eboon-05** [comment]
I have the same issue. I use quickshell from cachyos-extra-v3 repo (not AUR, luckily). I have a bar that follows a structure like this:

```qml
PanelWindow {
    RowLayout {
        Row { ... } // Wokspaces
        Item {
            Layout.fillWidth: true
        }
        Row { ... } // PipeWire
        Rectangle { ... } // A separator
        Row { ... } // Battery and so on
    }
}
```

I have the latest version to date:
```
$ sudo pacman -Qs quickshell
local/quickshell 0.3.0-2.1
    Flexible toolkit for making desktop shells with QtQuick
```
